// frontend/src/app/table-for-csv/table-for-csv.component.ts
import {Component, Input, OnChanges, OnInit} from '@angular/core';

@Component({
  selector: 'app-table-for-csv',
  templateUrl: './table-for-csv.component.html',

})

export class TableForCsvComponent implements OnInit, OnChanges {

  @Input('header') header;
  @Input('lines') lines;
  constructor() {

  }

  ngOnInit() {

  }
  ngOnChanges() {
  }

}

<div class="container mt-4">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th *ngFor="let item of header">{{item}}</th>
      </tr>
    </thead>
    <tbody>

      <tr *ngFor="let line of lines">
        <td *ngFor="let cell of line">{{cell}}</td>
      </tr>
    </tbody>
  </table>
</div>

// frontend-react-jsx/src/components/table-for-csv.js
import React, { Component } from 'react';

class TableForCsv extends React.Component {
    constructor(props) {
        super(props);
    }

    render() {
        let Table = '';
        if (this.props.tableheader) {

            const TableTh = this.props.tableheader.map((item) => <th>{item}</th> );
            const TableCells = this.props.tabledata.map((line) =>  <tr>{line.map((cell) => <td>{cell}</td>)}</tr>);

            Table = <div className="container mt-4">
                <table className="table table-striped table-bordered table-hover">
                    <thead>
                        <tr>{TableTh}</tr>
                    </thead>
                    <tbody>
                        {TableCells}
                    </tbody>
                </table>
            </div>
        }
        return Table;
    }
}
export default TableForCsv;
